### ISSUE TITLE
Entropy of q(y|x)

### ISSUE THREAD

**Issue by TuTanK5** [RuiShu/vae-clustering#6]
In the code, you maximize the entropy of q(y|x) by minimize the negative entropy. 

I think we want to make Y more informative so we should minimize the entropy instead. What is the intuition behind maximizing it?

And why the entropy still get reduced by the training?

**Comment by RuiShu** [comment]
Good question. Two years ago, I'd have said that "you maximize the entropy because that's what Variational Bayes tells you to do." That is to say, if you _wish_ to adhere to maximum likelihood training, then you want your variational posterior to faithfully copy the true posterior, then the Evidence Lower Bound construction forces you to include a term that pulls q(y|x) toward your prior.

The reason why it is _possible_ for entropy to still reduce during training is that the Evidence Lower Bound is, in some sense, "information-neutral" insofar as the your reconstruction term competes to make y informative, while the prior competes to make y uninformative.

Given access to an oracle optimizer and a maximally expressive posterior, you will then place your faith in maximum likelihood selecting a model that makes use of the latent variable.

----

Whether that actually happens is another matter :)

**Comment by TuTanK5** [comment]
Thank you. That clarifies my doubt.
